[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
  { access = "read-write", path = "./"},
]

remappings = [
  '@chainlink/local/=lib/chainlink-local/',
  '@chainlink/contracts-ccip/=lib/chainlink-local/lib/ccip/contracts/',
  'forge-std/=lib/forge-std/src/',
  ### NOTE: use eigenlayer's openzeppelin dependencies
  '@openzeppelin/contracts/=lib/eigenlayer-contracts/lib/openzeppelin-contracts/contracts',
  '@openzeppelin/contracts-upgradeable/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable/contracts'
]

[rpc_endpoints]
localhost = "http://localhost:8545"
holesky = "https://holesky.drpc.org"
## Note: Free RPCs may sometimes fail when deploying and verifying contracts.
# ethsepolia = "https://sepolia.drpc.org"
ethsepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
basesepolia = "https://sepolia.base.org"

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }
ethsepolia = { key = "${ETHERSCAN_API_KEY}" }
basesepolia = { key = "${BASESCAN_API_KEY}" }
