[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read-write", path = "./"},
]

remappings = [
  '@chainlink/local/=lib/chainlink-local/',
  '@chainlink/contracts-ccip/=lib/chainlink-local/lib/ccip/contracts/',
  'forge-std/=lib/forge-std/src/',
  ### NOTE: use eigenlayer's openzeppelin dependencies
  '@openzeppelin/contracts/=lib/eigenlayer-contracts/lib/openzeppelin-contracts/contracts',
  '@openzeppelin/contracts-upgradeable/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable/contracts'
]

[rpc_endpoints]
localhost = "http://localhost:8545"
holesky = "https://holesky.drpc.org"
## Note: Free RPCs may sometimes fail when deploying and verifying contracts.
# arbsepolia = "https://sepolia-rollup.arbitrum.io/rpc"
# arbsepolia = "https://arbitrum-sepolia.blockpi.network/v1/rpc/public"
# ethsepolia = "https://sepolia.drpc.org"
# ethsepolia = "https://sepolia.gateway.tenderly.co"
ethsepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
arbsepolia = "https://arbitrum-sepolia.infura.io/v3/${INFURA_API_KEY}"

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }
ethsepolia = { key = "${ETHERSCAN_API_KEY}" }
arbsepolia = { key = "${ARBISCAN_API_KEY}" }
